# Generated by Django 3.2 on 2024-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.TextField(choices=[('User', 'user'), ('Moderator', 'moderator'), ('Admin', 'admin')], default='user', verbose_name='Роль'),
        ),
    ]
