# Generated by Django 3.2 on 2024-08-07 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240803_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение года выпуска не может быть отрицательным'), django.core.validators.MaxValueValidator(2024, message='Значение года выпуска не может быть больше текущего года')], verbose_name='Год выпуска'),
        ),
    ]
