# Generated by Django 3.2 on 2024-08-17 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240809_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'ordering': ('-pub_date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(10, message='Введенная оценка ниже допустимой'), django.core.validators.MaxValueValidator(1, message='Введенная оценка выше допустимой')], verbose_name='Оценка'),
        ),
    ]
